version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql_host
    restart: always
    env_file: ./env/mysql.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d

volumes:
  mysql_data:
    driver: local
