version: '3'

services:
  db:
    image: mysql:5.7
    env_file: ./env/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: express-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 3000:3000
    volumes:
      - .:/backend
      - node_modules:/backend/node_modules
    depends_on:
      - db

volumes:
  node_modules:
    driver: local
  mysql_data:
    driver: local
