# @name Root
GET http://localhost:3000 HTTP/1.1
Content-Type: application/json

###

# @name Signin
POST http://localhost:3000/signin HTTP/1.1
Content-Type: application/json

{
  "email": "hoge@example.com",
  "password": "hoge"
}

###

# @name GetUsers
GET http://localhost:3000/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer

###

# @name PostUsers
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer

{
  "email": "test10@example.com",
  "name": "test10",
  "password": "test10"
}
